spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5000MB
      max-request-size: 5000MB

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        proc:
          param_null_passing: true
        enable_lazy_load_no_trans: true
        check_nullabiglity: true
        dialect: org.hibernate.dialect.SQLServer2008Dialect
    show-sql: true
  datasource:
    url: "jdbc:postgresql://dpg-ct76sg3tq21c73bju9qg-a.oregon-postgres.render.com/lpa_app"ss
    sqlScriptEncoding: UTF-8
    driver-class-name: org.postgresql.Driver
    username: lpa_app_user
    password: 4ZExWumairHN9I5kQVYO2ntBqsipnscj
    hikari:
      max-lifetime: 30
#  datasource:
#    url: "jdbc:sqlserver://localhost:1433;database=SHE"
#    sqlScriptEncoding: UTF-8
#    username: sa
#    password: 18
#    hikari:
#      max-lifetime: 30

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
  api-docs:
    path: "/api-docs"

spring.mail:
  host: smtp.gmail.com
  port: 587
  username: anhle180101@gmail.com
  password: ftzipjplmsdeycid
  properties.mail.smtp:
    auth: true
    starttls:
      enable: true

jwkPublicFile: classpath:jwt-public.json
jwkFile: classpath:jwt.json

logging:
  level:
    ROOT: INFO
server:
  error:
    include-message: always
    include-binding-errors: always

firebase:
  bucket-name: fir-myshop-lpa.appspot.com
  image-url: https://storage.googleapis.com/${firebase.bucket-name}/%s
  prefix-image-url: https://firebasestorage.googleapis.com/v0/b/${firebase.bucket-name}/o/
  suffix-image-url: ?alt=media

# social login
GOOGLE_CLIENT_ID: 387422189053-5ojrdmslj960485j5u7n0p0kaheldf2l.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET: 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
GOOGLE_REDIRECT_URI:  https://pa-shop-api.up.railway.app/api/auth/oauth2/google
RESPONSE_URI: https://shop-ptit.vercel.app/oauth2/redirect?
GOOGLE_LINK_GET_TOKEN: https://accounts.google.com/o/oauth2/token
GOOGLE_LINK_GET_USER: https://www.googleapis.com/oauth2/v1/userinfo?access_token=

vnpay:
  vnp_Version: 2.1.0
  vnp_Command: pay
  vnp_Locale: vn
  vnp_OrderType: '200000'  # don hang thoi trang
  vnp_BankCode: ''
  vnp_PayUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  vnp_Returnurl_dev: http://localhost:8080/api/payment/vnpay/result/VnPayIPN
  vnp_Returnurl: http://localhost:8080/api/payment/vnpay/result/VnPayIPN
  vnp_TmnCode: BN42ML7M
  vnp_HashSecret: MJHFWENMTHYIASYHDHHMPSJKOSQNNSXF
  vnp_ApiUrl: http://sandbox.vnpayment.vn/merchant_webapi/merchant.html
  url_response_ui_dev: http://localhost:3000/result-payment/
  url_response_ui: http://localhost:3000/result-payment/
  vnp_Salt: AnhJun18

ghtk:
  TOKEN: 700a2a511c4730b289ad27ab100b9de838ca07bd
  API_ENDPOINT: https://services-staging.ghtklab.com
  CREATE_ORDER_URL: ${ghtk.API_ENDPOINT}/services/shipment/order/?ver=1.5
  CALCUATE_SHIP_FEE_URL: ${ghtk.API_ENDPOINT}/services/shipment/fee
  CHECKING_STATUS_URL: ${ghtk.API_ENDPOINT}/services/shipment/v2/
  PRINT_INVOICE: ${ghtk.API_ENDPOINT}/services/label/
  CANCEL_ORDER_URL: ${ghtk.API_ENDPOINT}/services/shipment/cancel/
  PICK_PROVINCE: TP Hồ Chí Minh
  PICK_DISTRICT: Tăng Nhơn Phú A
  GHTK_HASHSECRET: PA18AAIN38HT36HKILS43MGPTITV32BM2KHHS3PA923
  SALT: PA2001Jun