spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  datasource:
    url: "jdbc:sqlserver://anhjun18.database.windows.net:1433;database=MyShop"
    useUnicode: yes
    sqlScriptEncoding: UTF-8
    username: pa
    password: 123456qQ
    hikari:
      max-lifetime: 30

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
  api-docs:
    path: "/api-docs"

spring.mail:
  host: smtp.gmail.com
  port: 587
  username: anhle180101@gmail.com
  password: ftzipjplmsdeycid
  properties.mail.smtp:
        auth: true
        starttls:
            enable: true

jwkPublicFile: classpath:jwt-public.json
jwkFile: classpath:jwt.json

logging:
  level:
    ROOT: INFO

firebase:
  bucket-name: fir-myshop-lpa.appspot.com
  image-url: https://storage.googleapis.com/${firebase.bucket-name}/%s
  prefix-image-url: https://firebasestorage.googleapis.com/v0/b/${firebase.bucket-name}/o/
  suffix-image-url: ?alt=media
